# Generated by Django 4.1.9 on 2023-05-16 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpFormulaVCST',
            fields=[
                ('FCSKID', models.CharField(db_column='FCSKID', editable=False, max_length=8, primary_key=True, serialize=False, verbose_name='ID')),
                ('FCCODE', models.CharField(db_column='FCCODE', max_length=20, verbose_name='รหัส')),
                ('FCNAME', models.CharField(db_column='FCNAME', max_length=50, verbose_name='ชื่อ')),
                ('FCNAME2', models.CharField(blank=True, db_column='FCNAME2', max_length=255, verbose_name='ข้อมูลเพิ่มเติม')),
                ('FCADDR1', models.CharField(blank=True, db_column='FCADDR1', max_length=50, verbose_name='FCADDR1')),
                ('FCADDR12', models.CharField(blank=True, db_column='FCADDR12', max_length=50, verbose_name='FCADDR12')),
                ('FCADDR2', models.CharField(blank=True, db_column='FCADDR22', max_length=50, verbose_name='FCADDR22')),
                ('FCTEL', models.CharField(blank=True, db_column='FCTEL', max_length=50, verbose_name='FCTEL')),
                ('FCFAX', models.CharField(blank=True, db_column='FCFAX', max_length=50, verbose_name='FCFAX')),
                ('FTDATETIME', models.DateTimeField(auto_now_add=True, db_column='FTDATETIME', verbose_name='สร้างเมื่อ')),
                ('FTLASTEDIT', models.DateTimeField(auto_now=True, db_column='FTLASTEDIT', verbose_name='แก้ไขเมื่อ')),
                ('FTLASTUPD', models.DateTimeField(auto_now=True, db_column='FTLASTUPD', verbose_name='อัพเดทเมื่อ')),
                ('FCTAXID', models.CharField(blank=True, db_column='FCTAXID', max_length=50, verbose_name='FCTAXID')),
            ],
            options={
                'verbose_name': 'รายชื่อบริษัท',
                'verbose_name_plural': 'รายชื่อบริษัท',
                'db_table': 'CORP',
            },
        ),
        migrations.CreateModel(
            name='PdGrdFormulaVCST',
            fields=[
                ('FCSKID', models.CharField(db_column='FCSKID', editable=False, max_length=8, primary_key=True, serialize=False, verbose_name='ID')),
                ('FCCODE', models.CharField(db_column='FCCODE', max_length=20, verbose_name='รหัส')),
                ('FCNAME', models.CharField(db_column='FCNAME', max_length=20, verbose_name='ชื่อ')),
                ('FCNAME2', models.CharField(db_column='FCNAME2', max_length=20, verbose_name='ข้อมูลเพิ่มเติม')),
                ('FTDATETIME', models.DateTimeField(auto_now_add=True, db_column='FTDATETIME', verbose_name='สร้างเมื่อ')),
                ('FTLASTEDIT', models.DateTimeField(auto_now=True, db_column='FTLASTEDIT', verbose_name='แก้ไขเมื่อ')),
                ('FTLASTUPD', models.DateTimeField(auto_now=True, db_column='FTLASTUPD', verbose_name='อัพเดทเมื่อ')),
            ],
            options={
                'verbose_name': 'ข้อมูลกลุ่ม',
                'verbose_name_plural': 'กลุ่มสินค้า',
                'db_table': 'PDGRP',
            },
        ),
        migrations.CreateModel(
            name='ProductTypeFormulaVCST',
            fields=[
                ('FCSKID', models.CharField(db_column='FCSKID', editable=False, max_length=8, verbose_name='ID')),
                ('FCCODE', models.CharField(db_column='FCCODE', max_length=20, primary_key=True, serialize=False, verbose_name='รหัส')),
                ('FCNAME', models.CharField(db_column='FCNAME', max_length=20, verbose_name='ชื่อ')),
                ('FCNAME2', models.CharField(db_column='FCNAME2', max_length=20, verbose_name='ข้อมูลเพิ่มเติม')),
                ('FTDATETIME', models.DateTimeField(auto_now_add=True, db_column='FTDATETIME', verbose_name='สร้างเมื่อ')),
                ('FTLASTEDIT', models.DateTimeField(auto_now=True, db_column='FTLASTEDIT', verbose_name='แก้ไขเมื่อ')),
                ('FTLASTUPD', models.DateTimeField(auto_now=True, db_column='FTLASTUPD', verbose_name='อัพเดทเมื่อ')),
            ],
            options={
                'verbose_name': 'ประเภทสินค้า',
                'verbose_name_plural': 'ประเภทสินค้า',
                'db_table': 'PRODTYPE',
            },
        ),
        migrations.CreateModel(
            name='UmFormulaVCST',
            fields=[
                ('FCSKID', models.CharField(db_column='FCSKID', editable=False, max_length=8, primary_key=True, serialize=False, verbose_name='ID')),
                ('FCCODE', models.CharField(db_column='FCCODE', max_length=20, verbose_name='รหัส')),
                ('FCNAME', models.CharField(db_column='FCNAME', max_length=20, verbose_name='ชื่อ')),
                ('FCNAME2', models.CharField(db_column='FCNAME2', max_length=20, verbose_name='ข้อมูลเพิ่มเติม')),
                ('FTDATETIME', models.DateTimeField(auto_now_add=True, db_column='FTDATETIME', verbose_name='สร้างเมื่อ')),
                ('FTLASTEDIT', models.DateTimeField(auto_now=True, db_column='FTLASTEDIT', verbose_name='แก้ไขเมื่อ')),
                ('FTLASTUPD', models.DateTimeField(auto_now=True, db_column='FTLASTUPD', verbose_name='อัพเดทเมื่อ')),
            ],
            options={
                'verbose_name': 'ข้อมูลหน่วยสินค้า',
                'verbose_name_plural': 'หน่วยสินค้า',
                'db_table': 'UM',
            },
        ),
        migrations.CreateModel(
            name='WhouseFormulaVCST',
            fields=[
                ('FCSKID', models.CharField(db_column='FCSKID', editable=False, max_length=8, primary_key=True, serialize=False, verbose_name='ID')),
                ('FCCODE', models.CharField(db_column='FCCODE', max_length=20, verbose_name='รหัส')),
                ('FCNAME', models.CharField(db_column='FCNAME', max_length=20, verbose_name='ชื่อ')),
                ('FCNAME2', models.CharField(db_column='FCNAME2', max_length=20, verbose_name='ข้อมูลเพิ่มเติม')),
                ('FTDATETIME', models.DateTimeField(auto_now_add=True, db_column='FTDATETIME', verbose_name='สร้างเมื่อ')),
                ('FTLASTEDIT', models.DateTimeField(auto_now=True, db_column='FTLASTEDIT', verbose_name='แก้ไขเมื่อ')),
                ('FTLASTUPD', models.DateTimeField(auto_now=True, db_column='FTLASTUPD', verbose_name='อัพเดทเมื่อ')),
            ],
            options={
                'verbose_name': 'ข้อมูลคลังสินค้า',
                'verbose_name_plural': 'คลังสินค้า',
                'db_table': 'WHOUSE',
            },
        ),
        migrations.CreateModel(
            name='ProductFormulaVCST',
            fields=[
                ('FCSKID', models.CharField(db_column='FCSKID', editable=False, max_length=8, primary_key=True, serialize=False, verbose_name='ID')),
                ('FCCODE', models.CharField(db_column='FCCODE', max_length=20, verbose_name='รหัส')),
                ('FCNAME', models.CharField(db_column='FCNAME', max_length=20, verbose_name='ชื่อ')),
                ('FCNAME2', models.CharField(db_column='FCNAME2', max_length=20, verbose_name='เพิ่มเติม1')),
                ('FCSNAME', models.CharField(db_column='FCSNAME', max_length=20, verbose_name='เพิ่มเติม2')),
                ('FCSNAME2', models.CharField(db_column='FCSNAME2', max_length=20, verbose_name='เพิ่มเติม3')),
                ('FCDATASER', models.CharField(db_column='FCDATASER', editable=False, max_length=20, verbose_name='รหัสจำเพราะ')),
                ('FTDATETIME', models.DateTimeField(auto_now_add=True, db_column='FTDATETIME', verbose_name='สร้างเมื่อ')),
                ('FTLASTEDIT', models.DateTimeField(auto_now=True, db_column='FTLASTEDIT', verbose_name='แก้ไขเมื่อ')),
                ('FTLASTUPD', models.DateTimeField(auto_now=True, db_column='FTLASTUPD', verbose_name='อัพเดทเมื่อ')),
                ('FCCORP', models.ForeignKey(db_column='FCCORP', on_delete=django.db.models.deletion.CASCADE, to='systemvcstapp.corpformulavcst', verbose_name='ชื่อบริษัท')),
                ('FCPDGRP', models.ForeignKey(db_column='FCPDGRP', on_delete=django.db.models.deletion.CASCADE, to='systemvcstapp.pdgrdformulavcst', verbose_name='กลุ่ม')),
                ('FCTYPE', models.ForeignKey(db_column='FCTYPE', on_delete=django.db.models.deletion.CASCADE, to='systemvcstapp.producttypeformulavcst', verbose_name='ประเภท')),
                ('FCUM', models.ForeignKey(db_column='FCUM', on_delete=django.db.models.deletion.CASCADE, to='systemvcstapp.umformulavcst', verbose_name='หน่วย')),
            ],
            options={
                'verbose_name': 'รายการข้อมูลสินค้า',
                'verbose_name_plural': 'รายการสินค้า',
                'db_table': 'PROD',
            },
        ),
    ]
